[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "ZIxgIcoXld"
weight = 9_999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "ZIxgIcoXl2"
weight = 9_999

[[main]]
name = "About"
url = "/about"
identifier = "soIZA0asbA"
weight = 9_999

[[footer]]
none = "none"